# Site settings
title: Architect Steven Baecke
email: info@stevenbaecke.be
description: Architect Steven Baecke
baseurl: ""
url: "https://stevenbaecke.be"
lang: "nl"
github_username: "archstevenb"
repository: "archstevenb/stevenbaecke.be"
remote_theme: bert-bruggeman/base-jekyll-theme


# favicon settings
favicon-theme-color: #ffffff

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-assets
  - jekyll-email-protect
  - jekyll-include-cache

# Includes
include:
  - _pages
  - _collections

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .git

# Do not process folders
keep_files:
  - favicons
  - media

# Collections
collections_dir: _collections
collections:
  forms:
    output: false

# Defaults
defaults:
  - scope:
      type: pages
    values:
      og-type: article
      schema: "WebSite"
  - scope:
      type: pages
      path: _pages
    values:
      schema: "WebPage"
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:year-:month-:day-:title:output_ext
      incremental: true
      og-type: blog
      schema: BlogPosting

# Image styles
image_styles:
  quality: 75
  card:
    width: 160
    height: 160
    sizes:
    - media: 'min-width: 1120px'
      width: 560
      height: 560
    - media: 'min-width: 960px'
      width: 480
      height: 480
    - media: 'min-width: 800px'
      width: 400
      height: 400
    - media: 'min-width: 640px'
      width: 320
      height: 320
    - media: 'min-width: 480px'
      width: 240
      height: 240
    - media: 'min-width: 400px'
      width: 200
      height: 200
  card-sidebar:
    width: 320
    height: 320
    sizes:
    - media: 'min-width: 1120px'
      width: 400
      height: 400
    - media: 'min-width: 960px'
      width: 320
      height: 320
    - media: 'min-width: 720px'
      width: 240
      height: 240
    - media: 'min-width: 640px'
      width: 560
      height: 560
    - media: 'min-width: 480px'
      width: 400
      height: 400
  card-wide:
    width: 360
    height: 180
    sizes:
    - media: 'min-width: 1280px'
      width: 960
      height: 480
    - media: 'min-width: 1120px'
      width: 720
      height: 360
    - media: 'min-width: 960px'
      width: 640
      height: 320
    - media: 'min-width: 720px'
      width: 720
      height: 360
    - media: 'min-width: 640px'
      width: 640
      height: 320
    - media: 'min-width: 480px'
      width: 480
      height: 240

# liquid compress html
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# jekyll-assets
assets:
  source_maps: false
  destination: "/assets"
  compression: true
  digest: false
  gzip: true
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
  caching:
    path: ".jekyll-cache/assets"
    type: file
    enabled: true
  precompile: []
  raw_precompile: []
  cdn:
    baseurl: false
    destination: false
    url: null
  sources:
    - _assets
    - _assets/favicons
    - media
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  debug: true
